services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: proyectodb
    ports:
      - "5432:5432"
    volumes:
      - proyectodb_postgres-data:/var/lib/postgresql/data

volumes:
  proyectodb_postgres-data:
    external: true

